"""Asynchronous Python client for the Nature Remo Cloud API."""

from .client import API_BASE_URL, NatureRemoClient
from .exceptions import (
    NatureRemoApiError,
    NatureRemoAuthError,
    NatureRemoConnectionError,
    NatureRemoError,
    NatureRemoRateLimitError,
)
from .models import (
    ENERGY_UNIT_MULTIPLIERS,
    EVENT_HUMIDITY,
    EVENT_ILLUMINATION,
    EVENT_MOVEMENT,
    EVENT_TEMPERATURE,
    TV,
    Aircon,
    AirconModeRange,
    AirconSettings,
    ApplianceButton,
    ApplianceModel,
    Device,
    EchonetLiteProperty,
    Light,
    LightState,
    RateLimit,
    SensorValue,
    Signal,
    SmartMeter,
    TVState,
    User,
)

__version__ = "0.1.0"

__all__ = [
    "API_BASE_URL",
    "ENERGY_UNIT_MULTIPLIERS",
    "EVENT_HUMIDITY",
    "EVENT_ILLUMINATION",
    "EVENT_MOVEMENT",
    "EVENT_TEMPERATURE",
    "TV",
    "Aircon",
    "AirconModeRange",
    "AirconSettings",
    "ApplianceButton",
    "ApplianceModel",
    "Device",
    "EchonetLiteProperty",
    "Light",
    "LightState",
    "NatureRemoApiError",
    "NatureRemoAuthError",
    "NatureRemoClient",
    "NatureRemoConnectionError",
    "NatureRemoError",
    "NatureRemoRateLimitError",
    "RateLimit",
    "SensorValue",
    "Signal",
    "SmartMeter",
    "TVState",
    "User",
]
